### ISSUE TITLE
handle cashDeposit separately for winning and bet

### ISSUE THREAD

**Issue by incredibleLeitman** [Marko-Pajic/SlotMachine#11]
Currently you use "cashDeposit--" and "cashDeposit++" directly in your loops that determine the winning which results in some duplicated code and harder readability. I think this also kinda works against the gamelogic? If the user now manages to win, they are granted a bonus but does not pay the bet amount?

One way to make this simpler would be to first reduce the bet for every time the user wants to play,
and when hitting some lines grant a win bonus. This way the bonus has to be greater than just 1, otherwise the user cannot really make a profit 😏

**Comment by mayisa87** [comment]
[15:04, 15.8.2023] Isabella: Hi @~Marko!
I don't think that it means to move it out of the loop.
Currently you got the wagerAmount, like 3$ or whatever. But you only use it to check on what lines hor. and ver. needs to be checked.
[15:07, 15.8.2023] Isabella: But, you are not decreasing the over all amount so your cashDeposit. You only increase and decrease it when winning or losing. 
So he suggested, to have the cashDeposit to be used like an play bank, decrease it each time by the wager amount.
And then have a variable to check on winnings or losings and add this to the cashDeposit accordingly
