### ISSUE TITLE
Reduce your conditions in if

### ISSUE THREAD

**Issue by mayisa87** [Marko-Pajic/SlotMachine#14]
https://github.com/Marko-Pajic/SlotMachine/blob/55f2c676bc052a38952edba60175aad0ba4c3e02/Program.cs#L48

I had a look to your ifs conditions again, as you do the ifs in right sequence, you can reduce your conditions, as the wagerAmount should be always<=MAXIMUM_WAGER anyway. And as you use Math.MIN to extract the according iteration value, you can skip this second condition in ifs.

1. In first if check only, if the wagerAmount >= min, then you know, you need to check some horizontal lines.
2. At second if, check if the wagerAmount >GRID_ROW
3. At third if, check if >allRowsandColsChecked

If you want to handle an wagerAmount >MAXIMUM_WAGER, you could do a separate if before all others, to handle this case as an error and show it to user, that would be better.

**Comment by Marko-Pajic** [comment]
Sorry forgot the wagerAmount > MAXIMUM_WAGER situation. I will add that later.
