### ISSUE TITLE
Consider upperbound as not considered ;)

### ISSUE THREAD

**Issue by mayisa87** [Marko-Pajic/SlotMachine#19]
https://github.com/Marko-Pajic/SlotMachine/blob/d649fd957d40aed46b93a2d941c61aea736c828d/LogicMethods.cs#L27

Remember that .Next() method of the Random class does exclude the given upper bound, so if you want to have number between 1 and 6 you need to use 1 and UPPER_BOUND+1

**Comment by Marko-Pajic** [comment]
Hi Isabella.
If i want to keep it in the range of 1 to 5 do i write UPPER_BOUND = 5 and later +1 or can i leave it at 6?
Thank you :)
