### ISSUE TITLE
Avoid duplicated lines --> move after your ifs

### ISSUE THREAD

**Issue by mayisa87** [Marko-Pajic/SlotMachine#4]
https://github.com/Marko-Pajic/SlotMachine/blob/0917525f03fb79957e3cfa4e4fb17d84acfcd216/Program.cs#L61-L70

This code block is done everytime, for horizontal, vertical and diagonal check. 
So you could just move it after your ifs and do it only once :)

**Comment by Marko-Pajic** [comment]
Hi Isabella!
If i move it outside of IF statement how am I going to check if i need to reward the player for winning lines?
For example if iam checking all the horizontal lines and the second line is winning but not first and third...all that is done inside the IF  statement.
Thank you!

**Comment by mayisa87** [comment]
Yes you are right,  as you want to increase cashDeposit for each winning line. So you need it at this point. Sorry, so it is OK. Later on in next steps, we can maybe refactor this a bit by using methods. But this will be done later on 💪
