### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by incredibleLeitman** [Marko-Pajic/SlotMachine#7]
https://github.com/Marko-Pajic/SlotMachine/blob/6a730c96f2787e10737f23fc3b7118e2d12ff22e/Program.cs#L1
do you really need those using?

Get into the habit of checking all your usings regularly and at least before each commit

**Comment by Marko-Pajic** [comment]
Question should be..."The f*ck is this?" xD

I still dont understand how these usings appear. Maybe i typed something wrong and deleted after...have to read more about it.

**Comment by incredibleLeitman** [comment]
> Question should be..."The f*ck is this?" xD
> 
> I still dont understand how these usings appear. Maybe i typed something wrong and deleted after...have to read more about it.

xD

The reason is, sometimes you mistype a keyword and visual studio goes like "oh you want to use Microsoft.Cerfificats.Compilersettings? let me include that for you" 
but when you fix the typo Visual studio does not automatically remove this added usings.

We are searching for a solution to disable this "feature" in visual studio and try to make a video about that so that this behaviour should not occur

**Comment by Marko-Pajic** [comment]
Thanks man.  I learned today...Ctrl + R + G removes unused usings
